libpredweb/myfunc.py

add new function for pdb2seq which solves the problem in parsing PDB files with e.g. HD11

add new function for pdb2seq

---

.gitignore
libpredweb/test.py

test script for testing functions

add test script

---

libpredweb/myfunc.py
libpredweb/qd_fe_common.py
libpredweb/test.py

add function urlretrieve with timeout, set timeout to 10 sec

---

libpredweb/webserver_common.py

Change default url from http to https

feat: change default url from http to https

---

libpredweb/qd_fe_common.py
libpredweb/webserver_common.py

Merge the function SubmitJob() from web_topcons2. The web_topcons2 will use the module from libpredweb instead its own variant.

Feat: merge submitjob with topcons

---

libpredweb/qd_fe_common.py

Fix the bug that a non accessible node will block the following nodes

Fix: submitjob blocking node

---

src/job_final_process.py

Fix the syntax error in the function job_final_process.py

fix: syntax of using lower case

---

libpredweb/webserver_common.py

merge the function SubmitQueryToLocalQueue() from topcons2 and scampi2

Feat: merge submit query to local queue from topcons2 scampi2

---

libpredweb/webserver_common.py

this PR defines the function which obtain the name_server from name_software

feat: define function to get name_server from name_software

---

requirements.txt

This PR fixes vulnerabilities for the libpredweb

fix: solve vulnerabilities

---

libpredweb/webserver_common.py

fix: determine name_server from name_software dynamically

---

libpredweb/qd_fe_common.py

This PR merge the code for RunStatistics from topcons2

Feat: merge run statistics from topcons2

---

setup.py
src/restart_qd_fe.cgi

This PR add the script restart_qd_fe.cgi to the library

feat: add script restart_qd_fe.cgi

---

libpredweb/qd_fe_common.py

This PR  makes the module `GetResult` working for topcons2 as well.

feat: merge GetResult from topcons2

---

libpredweb/qd_fe_common.py
libpredweb/webserver_common.py
src/clean_cached_result.py
src/job_final_process.py
src/run_server_statistics.py

This PR implements the separation of CleanCachedResult from qd

Feat: run clean cached result separately

---

libpredweb/webserver_common.py

This PR together with PR https://github.com/NBISweden/predictprotein-webserver-topcons2/pull/54 closes https://github.com/NBISweden/libpredweb/issues/20
Please have a look at http://dev.topcons.bioshu.se/pred/serverstatus/ to see the new interactive graphs. If you would like you can compare with the old png:s at https://topcons.cbr.su.se/pred/serverstatus/.

refactor: statistics file parsing

---

libpredweb/myfunc.py
src/run_server_statistics.py

This PR closes https://github.com/NBISweden/SysDev-Maple/issues/37
Two SQLite db files 
```
all_finished_job.sqlite3
all_submitted_job.sqlite3
```
are created. But the text files are still kept for easy manual verification.

Feat: sql analytic files

---

libpredweb/webserver_common.py

use submission counting from both web interface and wsdl

---

libpredweb/qd_fe_common.py

This PR adds DEBUG info for MAX_TIME_IN_REMOTE_QUEUE

add DEBUG info for MAX_TIME_IN_REMOTE_QUEUE

---

libpredweb/qd_fe_common.py
setup.py

This PR enables the usage of IP also as the VIP user so that the priority can be controlled on demand.

Enable ip as vip user

---

libpredweb/qd_fe_common.py
src/run_server_statistics.py

This PR fixes the bug when the timefile includes null byte in the statistics script.

Fix: broken run statistics null byte

---

libpredweb/webserver_common.py

This PR improves the logic of the function get_job_status so that the job result folder is checked by os.path.exists() only when necessary.

checking folder existence only when necessary

---

libpredweb/myfunc.py
libpredweb/qd_fe_common.py
libpredweb/webserver_common.py

This PR add support for SCAMPI for the function CreateRunJoblog()

Add support for SCAMPI for the function CreateRunJoblog

---

README.md

fix errors in the readme
